global:
  domain: argocd.railguncnr.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.railguncnr.com
    tls: true
    extraTls:
      - secretName: wildcard-tls
        hosts:
          - argocd.railguncnr.com
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

dex:
  enabled: false
