defaultSettings:
  defaultReplicaCount: 2
  defaultDataPath: /var/lib/longhorn
  storageMinimalAvailablePercentage: 15
  defaultDataLocality: best-effort

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2

ingress:
  enabled: false
