apiVersion: v1
kind: Secret
metadata:
  name: gitlab-initial-root-password
  namespace: devops
type: Opaque
stringData:
  # DEGISTIR: GitLab root sifreni buraya yaz
  password: "GITLAB_ROOT_PASSWORD_BURAYA"
