apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: devops
type: Opaque
stringData:
  # GitLab kurulduktan sonra runner registration token'i buraya ekle
  # GitLab Admin > CI/CD > Runners > Register a runner
  runner-registration-token: ""
  # GitLab 16+ icin authentication token kullanilir
  runner-token: ""
